### ISSUE TITLE
MessagePump retry behavior should be configurable

### ISSUE THREAD

**Issue by scott-ngan-cko** [Im5tu/OpenMessage#136]
Message pump retry behaviour should be configurable. At the moment it performs an immediate retry in a while loop which causes the pump to hammer the service if it is not available:

https://github.com/Im5tu/OpenMessage/blob/d0dbaa4249f772ac0f7111dac588fb0daf808d2e/src/OpenMessage.AWS.SQS/SqsMessagePump.cs#L31-L57

The behaviour may need to be lifted up into `MessagePump<T>` and should ideally make use of polly policies

**Comment by scott-ngan-cko** [comment]
When dealing with docker and localstack, the message pump services are usually spun up much faster/sooner than the localstack resources.

While it doesn't break anything, it causes a lot of noise in the logs

**Comment by scott-ngan-cko** [comment]
Would also 

- Prevent the pump from looking like a DoS attack
- Reduce load on the messaging provider
- Avoid issues where hammering an uninitialised messaging provider stops it from even starting up

**Comment by Im5tu** [comment]
I've a simple wait 5 seconds for now, need to think about this more before I put polly in there as a dependency. Will leave this open so we can talk through next week

**Comment by scott-ngan-cko** [comment]
Was thinking that the polly dependency would live in an extension package.
