### ISSUE TITLE
Would like to configure MaxConcurrentCalls on subscriptions.

### ISSUE THREAD

**Issue by dallancarr** [Im5tu/OpenMessage#18]

**Comment by danielcirket** [comment]
I know myself and @Im5tu have been discussing a better way to do the initial service registration with the possibility of exposing a configuration builder / options provider to make the whole thing easier for consumers, so this should be considered/included with those updates if they go ahead

**Comment by dallancarr** [comment]
Thanks for replying. Also would be good to get the async callback in as standard somewhere in the backlog.

**Comment by Im5tu** [comment]
As Dan mentioned, we are looking into how best to structure the API surface prior to the 1.0 release. Ideas welcome! I'll see that this is included for that release :)
