### ISSUE TITLE
ConfigureAllHandlers isn't discovering handlers when running as a unit test

### ISSUE THREAD

**Issue by scott-ngan-cko** [Im5tu/OpenMessage#216]
https://github.com/Im5tu/OpenMessage/blob/c7203b177bae7e30262721e135a8f68eb8f7cf42/src/OpenMessage/OpenMessageExtensions.cs#L250

In a unit test, when running `.ConfigureAllHandlers()`, then `IHandler<>` types are not found because the entry assembly is the test host:

```
testhost, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
```

We should consider using a different assembly (`Assembly.GetExecutingAssembly()`) or take in a specific class `.ConfigureAllHandlers<Program>()`

**Comment by scott-ngan-cko** [comment]
We should also raise an exception if there are no registered `IHandler<>`s

**Comment by Im5tu** [comment]
Done as part of null ref types: https://github.com/Im5tu/OpenMessage/commit/fa745d49d91a4be63352e2326ba1d02ab8eb8a26#diff-521cc66fdaf7834130ad3ee76cf28672L250
