### ISSUE TITLE
Create Event Hubs Provider

### ISSUE THREAD

**Issue by Im5tu** [Im5tu/OpenMessage#5]
To go along with the Service Bus provider, we should also have one for Event Hubs

**Comment by Im5tu** [comment]
As discussed privately on twitter, if the event hubs have the same dependencies then include in the same project otherwise split out to `.Azure.<specific>`.

I'll write a PR tomorrow to mark the old extension methods as obsolete in favour of the building context description.

**Comment by danielcirket** [comment]
Just a note to say this will be trackable under the feature/AzureEventHubsProvider branch

**Comment by Im5tu** [comment]
@danielcirket - closing as over 2 years old. Feel free to jump in with the new implementation that i'm working on
